import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: ["class"],
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-container-lowest": "#ffffff",
        "on-secondary": "#ffffff",
        "surface-container": "#eaedff",
        "secondary-fixed-dim": "#93ccff",
        "on-tertiary-fixed-variant": "#3a485b",
        primary: {
          DEFAULT: "#00685f",
          50: "#f0fdf9",
          100: "#ccfbf0",
          200: "#99f6e3",
          300: "#5eead3",
          400: "#2dd4be",
          500: "#0d9488",
          600: "#00685f",
          700: "#0f766e",
          800: "#115e58",
          900: "#134e49",
        },
        "on-primary-fixed-variant": "#005049",
        "inverse-on-surface": "#eef0ff",
        "surface-container-high": "#e2e7ff",
        "on-error-container": "#93000a",
        "inverse-surface": "#283044",
        "surface-bright": "#faf8ff",
        "secondary-fixed": "#cce5ff",
        "on-tertiary": "#ffffff",
        "on-tertiary-fixed": "#0d1c2e",
        "primary-fixed": "#89f5e7",
        outline: "#6d7a77",
        "on-surface-variant": "#3d4947",
        "primary-container": "#008378",
        "tertiary-container": "#67758b",
        surface: "#faf8ff",
        "surface-container-highest": "#dae2fd",
        "on-primary-fixed": "#00201d",
        "tertiary-fixed": "#d5e3fc",
        "surface-dim": "#d2d9f4",
        "on-primary": "#ffffff",
        "on-tertiary-container": "#fdfcff",
        "on-background": "#131b2e",
        "on-secondary-fixed-variant": "#004b73",
        "on-primary-container": "#f4fffc",
        "on-secondary-fixed": "#001d31",
        secondary: {
          DEFAULT: "#006398",
          container: "#5bb8fe",
        },
        tertiary: {
          DEFAULT: "#4f5d71",
        },
        "secondary-container": "#5bb8fe",
        "primary-fixed-dim": "#6bd8cb",
        "on-surface": "#131b2e",
        "error-container": "#ffdad6",
        "surface-container-low": "#f2f3ff",
        error: {
          DEFAULT: "#ba1a1a",
        },
        "surface-variant": "#dae2fd",
        "on-error": "#ffffff",
        "inverse-primary": "#6bd8cb",
        "tertiary-fixed-dim": "#b9c7df",
        "outline-variant": "#bcc9c6",
        "on-secondary-container": "#00476e",
        background: "#faf8ff",
        "surface-tint": "#006a61",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "page-max-width": "1280px",
        "gutter-mobile": "1rem",
        "space-1": "0.25rem",
        "space-2": "0.5rem",
        "space-3": "0.75rem",
        "space-4": "1rem",
        "space-5": "1.25rem",
        "space-6": "1.5rem",
        "space-8": "2rem",
        "space-10": "2.5rem",
        "space-12": "3rem",
        "space-16": "4rem",
        "gutter-desktop": "1.5rem",
      },
      fontFamily: {
        sans: ["Plus Jakarta Sans", "sans-serif"],
        "headline-xl": ["Plus Jakarta Sans", "sans-serif"],
        "headline-lg": ["Plus Jakarta Sans", "sans-serif"],
        "headline-md": ["Plus Jakarta Sans", "sans-serif"],
        "headline-sm": ["Plus Jakarta Sans", "sans-serif"],
        "body-lg": ["Plus Jakarta Sans", "sans-serif"],
        "body-md": ["Plus Jakarta Sans", "sans-serif"],
        "body-sm": ["Plus Jakarta Sans", "sans-serif"],
        "label-lg": ["Plus Jakarta Sans", "sans-serif"],
        "label-md": ["Plus Jakarta Sans", "sans-serif"],
        "label-sm": ["Plus Jakarta Sans", "sans-serif"],
        "data-metric": ["Plus Jakarta Sans", "sans-serif"],
      },
      fontSize: {
        "headline-xl": [
          "36px",
          { lineHeight: "44px", letterSpacing: "-0.02em", fontWeight: "700" },
        ],
        "headline-lg": [
          "28px",
          { lineHeight: "36px", letterSpacing: "-0.01em", fontWeight: "600" },
        ],
        "headline-md": [
          "20px",
          { lineHeight: "28px", letterSpacing: "-0.005em", fontWeight: "600" },
        ],
        "headline-sm": ["16px", { lineHeight: "24px", letterSpacing: "0em", fontWeight: "600" }],
        "body-lg": ["16px", { lineHeight: "24px", letterSpacing: "0em", fontWeight: "400" }],
        "body-md": ["14px", { lineHeight: "20px", letterSpacing: "0em", fontWeight: "400" }],
        "body-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.01em", fontWeight: "400" }],
        "label-lg": ["14px", { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "600" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.02em", fontWeight: "600" }],
        "label-sm": ["11px", { lineHeight: "14px", letterSpacing: "0.04em", fontWeight: "700" }],
        "data-metric": [
          "32px",
          { lineHeight: "38px", letterSpacing: "-0.02em", fontWeight: "700" },
        ],
        "data-metric-mobile": [
          "24px",
          { lineHeight: "30px", letterSpacing: "-0.01em", fontWeight: "700" },
        ],
      },
    },
  },
  plugins: [],
};
export default config;
